name 'devday'
maintainer 'Christoph Thiel'
maintainer_email 'ct@kki.org'
license 'All rights reserved'
description 'Installs/Configures devday env'
long_description 'Installs/Configures devday env'
version '0.1.0'
depends 'mysql', '~> 6.1'
depends 'rbenv'
